type: WORLD
layers:
  - type: BACKGROUND
    path: /textures/backgrounds/splash.png
  - type: TILE
    path: tile.layer
  - type: ENTITY
    path: entity.layer


triggers:

  onStart:
    events:
      - TIMELINE:
          object: start
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p>Welcome, Prince Setna, our newest apprentice sorcerer!</p>
                <p class="instruction"> Use the <span class="control">WASD</span> keys to move around.</p>

  onAcquireOpen:
    events:
      - ACQUIRE:
          object: wpi
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p class="instruction"><span class="control">Right click</span> on the door and write a spell to open it.</p>

  onDoorOpen:
    events:
      - DOOR_OPEN:
          object: !door {x: 8, y: 3}
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p>By Thoth, you're a natural!</p>
                <p class="instruction">Use <span class="control">W</span> to jump over the bombs.</p>

  onAcquireUrn:
    events:
      - ACQUIRE:
          object: snbt
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p>You can't jump over this bomb! You'll have to use ~~magic~~ to clear it.</p>
                <p class="instruction"><span class="control">Right click</span> above the bomb to cast a spell there.</p>
                <p class="instruction">Combine your two new words to summon an urn that will trigger it.</p>
 
  onExplode:
    events:
      - EXPLODE:
          object: bombyBoi
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p>Woah, that explosion was sick!</p>
                <p>Is that a statue.. of Thoth!?</p>
 
  onAcquireThoth:
    events:
      - ACQUIRE:
          object: DHwty
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: thoth
              name: Thoth
              text: |
                <p>You found my statue. Now, I dare you to find my Book!</p>


 