type: WORLD
layers:
  - type: BACKGROUND
    path: /textures/backgrounds/splash.png
  - type: TILE
    path: tile.layer
  - type: ENTITY
    path: entity.layer


triggers:

  onStart:
    events:
      - TIMELINE:
          object: start
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p>Welcome, Prince Setna! Now that you are an apprentice scribe, feel free to take a look
                around.</p>
                <p class="instruction">Hit <span class="control">escape</span> to close this dialog.</p>
                <p class="instruction"> Use the <span class="control">WASD</span> keys to move around.</p>

  onAcquireOpen:
    events:
      - ACQUIRE:
          object: wpi
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p class="instruction"><span class="control">Right click</span> on the door and write a spell to open it.</p>

  onDoorOpen:
    events:
      - DOOR_OPEN:
          object: !door {x: 8, y: 3}
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p>By Thoth, you're a natural!</p>
                <p class="instruction">Advance to the next puzzzle.</p>

  onAcquireUrn:
    events:
      - ACQUIRE:
          object: snbt
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: priest
              name: Imhotep
              text: |
                <p>That bomb looks dangerous! Better clear it somehow.</p>
                <p class="instruction">Combine your two new words to summon an urn on top of the bomb.</p>
                <p class="instruction">This will blow it up and clear the path ahead.</p>

  onPrayThoth:
    events:
      - PRAY:
          object: a statue
    actions:
      - SET_DIALOG:
          dialog:
            !dialog
              image: thoth
              name: Thoth
              text: |
                <p>Thoth hears your prayer!</p>